# notifications:
#   irc: 
#     channels: 
#       - "irc.freenode.net#nupic"
#   webhooks: http://issues.numenta.org:8081/travis

before_script:
  - sudo apt-get install texlive
  - sudo apt-get install pandoc-1.9.2

script: 
  - pandoc ${TRAVIS_BUILD_DIR}/HTM_CLA/HTM_Cortical_Learning_Algorithms.tex -f latex -t html -s -o test.html

after_script:
  # just verify the output can be seen
  - cat test.html
